version: 2.1

orbs:
  agentic-cli: cci-labs/agentic-cli@0.0.2

jobs:
  install-ai-clis:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      
      # Install Claude CLI
      - agentic-cli/install_claude:
          version: latest
          
      # Install Gemini CLI
      - agentic-cli/install_gemini:
          version: latest
          
      # Install Rovo CLI (Atlassian CLI)
      - agentic-cli/install_rovo:
          version: latest
          
      # Print versions of all installed CLIs
      - run:
          name: "Print Claude CLI Version"
          command: |
            echo "=== Claude CLI Version ==="
            claude --version || echo "Claude CLI not found in PATH"
            
      - run:
          name: "Print Gemini CLI Version"
          command: |
            echo "=== Gemini CLI Version ==="
            gemini --version || echo "Gemini CLI not found in PATH"
            
      - run:
          name: "Print Rovo CLI Version"
          command: |
            echo "=== Rovo CLI Version ==="
            acli --version || echo "Rovo CLI not found in PATH"


  test-claude-mcp:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - agentic-cli/setup_claude:
          version: "latest"
          node_version: "20"
          api_key_var: "ANTHROPIC_API_KEY"
      - agentic-cli/prompt_claude:
          prompt: |
            Please use the CircleCI MCP server to analyze our pipeline status.
            To determine what project to look up please look at the environment variables for CircleCI. 
          model: "sonnet"
          output_format: "text"
          timeout: 600
          save_output: true
          mcp_config: |
            {
              "mcpServers": {
                "circleci-mcp-server": {
                  "command": "npx",
                  "args": ["-y", "@circleci/mcp-server-circleci"],
                  "env": {
                    "CIRCLECI_TOKEN": "${CIRCLECI_TOKEN}",
                    "CIRCLECI_BASE_URL": "https://circleci.com"
                  }
                }
              }
            }
          allowed_tools: "Bash,Edit,FileRead,WebSearch,mcp__circleci-mcp-server"


workflows:
  ai-cli-setup:
    jobs:
      - install-ai-clis
      - test-claude-mcp