version: 2.1

orbs:
  agentic-cli: cci-labs/agentic-cli@0.0.9

workflows:
  issue_event_workflow:
    jobs:
      - agentic-cli/issue_event_claude:
          context: agentic
          webhook_body: << pipeline.trigger_parameters.webhook.body >>
          claude_model: sonnet
          allowed_associations: OWNER,MEMBER,COLLABORATOR
          github_api_token_var: GITHUB_API_TOKEN
          circleci_token_var: CIRCLECI_TOKEN
          debug_mode: true
          allowed_actions: opened,assigned