version: 2.1

orbs:
  agentic-cli: cci-labs/agentic-cli@0.0.7

workflows:
  issue_comment_workflow:
    jobs:
      - agentic-cli/issue_review_claude:
          context: agentic
          webhook_body: << pipeline.trigger_parameters.webhook.body >>
          claude_model: sonnet
          trigger_phrase: "/agentic-orb"
          allowed_associations: "OWNER,MEMBER,COLLABORATOR"
          debug_mode: true