version: 2.1

orbs:
  agentic-cli: cci-labs/agentic-cli@0.0.5

workflows:
  pr_review_workflow:
    jobs:
      - agentic-cli/pr_review_claude:
          context: agentic
          webhook_body: << pipeline.trigger_parameters.webhook.body >>
          claude_model: sonnet
          allowed_actions: opened,synchronize
          allowed_associations: OWNER,MEMBER,COLLABORATOR
          debug_mode: true
          exclude_draft: false